version: '3'

services:
  blackmesa:
    #    image: lacledeslan/gamesvr-blackmesa-freeplay
    build: docker
    network_mode: host
    #    command: sh -c "./steamcmd.sh +login anonymous +force_install_dir ${HOMEDIR}/bm +app_update 346680 +validate"
    #    command: sh -c "/home/steam/bm/srcds_run -game bms +hostname 'Tesseract Game' +map gasworks +maxplayers 3"
    ports:
      - "1-65535:1-65535"
    volumes:
#      - ./steam:/home/steam:rw
#      - ./server.cfg:/home/steam/bm/bms/cfg/server.cfg:rw
    environment:
      USER: steam
