version: '3'

services:
  blackmesa:
#    image: lacledeslan/gamesvr-blackmesa-freeplay
    build: docker
    network_mode: host
    command: sh -c "./srcds_run -game bms +hostname 'Tesseract Game' +map gasworks +maxplayers 24"
    ports:
      - "1-65535:1-65535"
    volumes:
#      - ./server.cfg:/app/bms/cfg/server.cfg:rw
      - ./home/steam/bm:/app:rw
    environment:
      USER: steam
      HOMEDIR: "/home/${USER}"
      STEAMCMDDIR: "${HOMEDIR}/steamcmd"
